services:
  postgres:
    image: postgres:17
    container_name: finance
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0623"
    ports:
      - "5432:5432"
    volumes:
      - finance_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  finance_postgres_data:
